SPOTIPY_CLIENT_ID: ''
SPOTIPY_CLIENT_SECRET: ''
SPOTIPY_REDIRECT_URI: ''
SPOTIPY_USERNAME: ''
daily_mixes:
    SPOTIPY_DAILY_MIX_1_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_2_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_3_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_4_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_5_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_6_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_7_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_8_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_9_PLAYLIST_URI: ''
    SPOTIPY_DAILY_MIX_10_PLAYLIST_URI: ''